base = '.\';
ConfirmedPatient={  
    'b10',...
    'b12',...
    'b13',...
    'b14',...
    'b15',...
    'b16',...
    'b17',...
    'b2' ,...
    'b3' ,...
    'b5' ,...
    'b6' ,...
    'b8' ,...
    'b9' ,...
    'm1' ,...
    'm10',...
    'm11',...
    'm12',...
    'm13',...
    'm14',...
    'm15',...
    'm16',...
    'm18',...
    'm19',...
    'm20',...
    'm3' ,...
    'm32',...
    'm33',...
    'm34',...
    'm35',...
    'm5' ,...
    'm7' ,...
    'm8' ,...
    'm9'};
savepath = '.\Dataset_NO_fatSatured_normV2';
if(~exist(savepath,'dir'))
    mkdir(savepath);
end
for p=1:numel(ConfirmedPatient)
    paz = ConfirmedPatient{p};
    disp(['Working on ' paz]);
    
    %loading of the MRI scan of the patient
    load([base filesep paz filesep 'mat_data' filesep 'volume.mat']);
    
    %extracting just the pre-contrast volume from the MRI scan
    data = data(:,:,:,1);
    
    %permutation to transform coronal plane in axial plane
    data = permute(data, [3 2 1]);
    
    %normalization of the volume in range [0;255]
    data=((data-min(data(:)))/(max(data(:))-min(data(:)))).*255;
    
	%saving the volume in .mat format
    imdb.volume = data;
    save([savepath filesep paz '_volume.mat' ], '-struct', 'imdb') ;
end