base = '.\';
savepath = '.\Dataset_fat_satured_normV2/cropped';
if(~exist(savepath,'dir'))
    mkdir(savepath);
end
ConfirmedPatient={
                  'b1',...
                  'b19',...
                  'b2',...
                  'b20',...
                  'b25',...
                  'b32',...
                  'b37',...
                  'b46',...
                  'b48',...
                  'b50',...
                  'b64',...
                  'b68',...
                  'b70',...
                  'b73',...
                  'b76',...
                  'b85',...
                  'b87',...
                  'b93',...
                  'm10',...
                  'm21',...
                  'm23',...
                  'm27',...
                  'm28',...
                  'm4',...
                  'm42',...
                  'm49',...
                  'm5',...
                  'm53',...
                  'm62',...
                  'm63',...
                  'm65',...
                  'm69',...
                  'm75',...
                  'm83',...
                  'm84',...
                  'm91',...
                  'm96',...
                  'm97',...
                  'm99'};
for p=1:numel(ConfirmedPatient)
    paz = ConfirmedPatient{p};
    disp(['Working on ' paz]);
    
	%loading of the MRI scan of the patient
    load([base paz filesep 'volume.mat']);
    
    %extracting just the pre-contrast volume from the MRI scan
    volume = volume(:,:,:,1);
    
    data=volume;
    
    %normalization of the volume in range [0;255]
    data=((data-min(data(:)))/(max(data(:))-min(data(:)))).*255;
    
	%saving the volume in .mat format
    imdb.volume = data;
    save([savepath filesep paz '_volume.mat' ], '-struct', 'imdb') ;
end