base = '.\';
savepath = '.\Dataset_fat_satured_normV2';
if(~exist(savepath,'dir'))
    mkdir(savepath);
end
ConfirmedPatient={
                   'b1',...
                   'b19',...
                   'b2',...
                   'b25',...
                   'b32',...
                   'b37',...
                   'b46',...
                   'b48',...
                   'b50',...
                   'b64',...
                   'b68',...
                   'b70',...
                   'b73',...
                   'b76',...
                   'b85',...
                   'b87',...
                   'b93',...
                   'm10',...
                   'm21',...
                   'm23',...
                   'm27',...
                   'm28',...
                   'm4',...
                   'm42',...
                   'm49',...
                   'm5',...
                   'm53',...
                   'm62',...
                   'm63',...
                   'm65',...
                   'm69',...
                   'm75',...
                   'm83',...
                   'm84',...
                   'm91',...
                   'm96',...
                   'm97',...
                   'm99',...
                   'b20'};
for p=1:numel(ConfirmedPatient)
    paz = ConfirmedPatient{p};
    disp(['Working on ' paz]);
    %loading of the MRI scan of the patient
    load([base paz filesep 'volume.mat']);
    %loading of the breast mask
    load([base filesep paz filesep 'bmaskbinaria.mat']);
    x(x>= 0.5)=1;
    x(x<  0.5) =0;
    
    %extracting just the pre-contrast volume from the MRI scan
    volume = volume(:,:,:,1);
    %application of the breast mask to the volume
    data_bm = volume.*x;
    %indexes just of the slices containing the breast mask
    [xx,yy,zz_bm] = ind2sub(size(x), find(x==1));
    zz_bm_idx = unique(zz_bm);
    %excluding the extreme slices
    data_bm = data_bm(:,:,zz_bm_idx(10:end-10));
    
    %normalization of the volume in range [0;255]
    data_bm=((data_bm-min(data_bm(:)))/(max(data_bm(:))-min(data_bm(:)))).*255;
    
    %saving the volume in .mat format
    imdb.volume = data_bm;
    save([savepath filesep paz '_volume.mat' ], '-struct', 'imdb') ;
end