base = '.\';
ConfirmedPatient={  
    'b12',...
    'b10',...
    'b13',...
    'b14',...
    'b15',...
    'b16',...
    'b17',...
    'b2' ,...
    'b3' ,...
    'b5' ,...
    'b6' ,...
    'b8' ,...
    'b9' ,...
    'm1' ,...
    'm10',...
    'm11',...
    'm12',...
    'm13',...
    'm14',...
    'm15',...
    'm16',...
    'm18',...
    'm19',...
    'm20',...
    'm3' ,...
    'm32',...
    'm33',...
    'm34',...
    'm35',...
    'm5' ,...
    'm7' ,...
    'm8' ,...
    'm9'};
savepath = '.\Dataset_NO_fatSatured_normV2';
if(~exist(savepath,'dir'))
    mkdir(savepath);
end
for p=1:numel(ConfirmedPatient)
    paz = ConfirmedPatient{p};
    disp(['Working on ' paz]);
    %loading of the MRI scan of the patient
    load([base filesep paz filesep 'mat_data' filesep 'volume.mat']);
    %loading of the breast mask
    load([base filesep paz filesep 'mat_data' filesep 'MROI_mask.mat']);
    load([base filesep paz filesep 'mat_data' filesep 'bmask_GS.mat']);
    
    %extracting just the pre-contrast volume from the MRI scan
    data = data(:,:,:,1);
    %application of the breast mask to the volume
    data_bm = data.*mask;
    
    %permutation to transform coronal plane in axial plane
    data_bm = permute(data_bm, [3 2 1]);
    mask = permute(mask, [3 2 1]);
    
    %indexes just of the slices containing the breast mask
    [xx,yy,zz_bm] = ind2sub(size(mask), find(mask==1));
    zz_bm_idx = unique(zz_bm);
    %excluding the extreme slices
    data_bm = data_bm(:,:,zz_bm_idx(10:end-10));
    
    %normalization of the volume in range [0;255]
    data_bm=((data_bm-min(data_bm(:)))/(max(data_bm(:))-min(data_bm(:)))).*255;
    
    %saving the volume in .mat format
    imdb.volume = data_bm;
    mkdir(savepath)
    save([savepath filesep paz '_volume.mat' ], '-struct', 'imdb') ;
end